require('dotenv').config();
const mongoose = require('mongoose');
const https = require('https');

const WordModel = require('./src/models/word.model');

const MONGO_URL = process.env.MONGO_URL_LOCAL || process.env.MONGO_URL;
const PEXELS_API_KEY = process.env.PEXELS_API_KEY;

const DEFAULT_IMAGES = [
  'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
  'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
];

const LIMIT_PER_RUN = 1000;

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function isBadImageUrl(url = '') {
  if (!url) return true;

  return (
    DEFAULT_IMAGES.includes(url) ||
    /loremflickr/i.test(url) ||
    /1516321318423-f06f85e504b3/i.test(url)
  );
}

function getBetterSearchQuery(word, mean, type) {
  const cleanWord = String(word || '').toLowerCase().trim();

  const queryMap = {
    a: 'letter a alphabet',
    about: 'conversation discussion',
    above: 'above sky',
    accept: 'handshake agreement',
    accident: 'car accident',
    across: 'crossing street',
    act: 'theater performance',
    action: 'person action',
    active: 'active lifestyle',
    activity: 'children activity',
    add: 'addition math',
    address: 'home address',
    adult: 'adult person',
    advice: 'advice consultation',
    afraid: 'scared person',
    after: 'after work',
    afternoon: 'afternoon sun',
    again: 'repeat action',
    age: 'birthday age',
    air: 'fresh air nature',
    airport: 'airport terminal',
    all: 'group of people',
    alone: 'person alone',
    along: 'walking along road',
    already: 'completed task',
    also: 'group together',
    although: 'contrast concept',
    always: 'daily routine',
    amazing: 'amazing landscape',
    angry: 'angry person',
    animal: 'wild animals',
    answer: 'answer question',
    any: 'many choices',
    apartment: 'apartment building',
    apple: 'apple fruit',
    april: 'spring flowers',
    area: 'city area',
    arm: 'human arm',
    around: 'around circle',
    arrive: 'arrival airport',
    art: 'art painting',
    artist: 'artist painting',
    ask: 'asking question',
    at: 'location pin',
    aunt: 'family woman',
    autumn: 'autumn leaves',
    away: 'travel away',
    baby: 'baby child',
    back: 'human back',
    bad: 'bad weather',
    bag: 'school bag',
    ball: 'soccer ball',
    banana: 'banana fruit',
    bank: 'bank building',
    base: 'base foundation',
    basketball: 'basketball',
    bath: 'bathroom bathtub',
    bathroom: 'bathroom',
    be: 'person standing',
    beach: 'beach sea',
    beautiful: 'beautiful nature',
    because: 'reason thinking',
    become: 'growth change',
    bed: 'bedroom bed',
    bedroom: 'bedroom',
    beer: 'beer glass',
    before: 'before after concept',
    begin: 'starting line',
    beginning: 'start road',
    behind: 'behind wall',
    believe: 'believe hope',
    below: 'below ground',
    best: 'winner trophy',
    better: 'improvement progress',
    between: 'between two people',
    bicycle: 'bicycle',
    big: 'big building',
    bike: 'bicycle',
    bill: 'restaurant bill',
    bird: 'bird',
    birthday: 'birthday cake',
    black: 'black color',
    blue: 'blue sky',
    boat: 'boat lake',
    body: 'human body',
    book: 'books reading',
    boot: 'boots shoes',
    bored: 'bored person',
    boring: 'boring meeting',
    born: 'newborn baby',
    borrow: 'borrowing book',
    boss: 'business boss',
    bottle: 'water bottle',
    box: 'cardboard box',
    boy: 'boy child',
    bread: 'bread loaf',
    break: 'coffee break',
    breakfast: 'breakfast table',
    bring: 'bringing gift',
    brother: 'brother family',
    brown: 'brown color',
    build: 'construction building',
    building: 'city building',
    bus: 'bus public transport',
    business: 'business meeting',
    busy: 'busy office worker',
    but: 'contrast concept',
    butter: 'butter bread',
    buy: 'shopping store',
    by: 'walking by street',
    cake: 'cake dessert',
    call: 'phone call',
    camera: 'camera photography',
    can: 'person can do',
    car: 'car road',
    card: 'credit card',
    career: 'career office',
    carrot: 'carrot vegetable',
    carry: 'carrying bag',
    cat: 'cat pet',
    catch: 'catch ball',
    center: 'city center',
    chair: 'chair furniture',
    chance: 'opportunity door',
    change: 'change direction',
    cheap: 'cheap sale',
    cheese: 'cheese food',
    chicken: 'chicken food',
    child: 'child playing',
    chocolate: 'chocolate',
    choose: 'choosing options',
    cinema: 'cinema theater',
    city: 'city street',
    class: 'classroom students',
    classroom: 'classroom school',
    clean: 'cleaning house',
    clear: 'clear sky',
    clever: 'smart student',
    climb: 'climbing mountain',
    clock: 'clock time',
    close: 'closed door',
    clothes: 'clothes wardrobe',
    cloudy: 'cloudy sky',
    club: 'social club',
    coat: 'winter coat',
    coffee: 'coffee cup',
    cold: 'cold winter',
    college: 'college campus',
    color: 'color palette',
    come: 'person coming',
    comfortable: 'comfortable sofa',
    company: 'company office',
    compare: 'compare charts',
    complete: 'completed checklist',
    computer: 'computer desk',
    concert: 'music concert',
    conversation: 'people talking',
    cook: 'cooking kitchen',
    cooker: 'kitchen stove',
    cooking: 'cooking food',
    cool: 'cool sunglasses',
    correct: 'correct answer',
    cost: 'price tag',
    could: 'ability concept',
    country: 'countryside landscape',
    course: 'online course',
    cousin: 'family cousins',
    cow: 'cow farm',
    cream: 'cream dessert',
    create: 'creative work',
    culture: 'cultural festival',
    cup: 'coffee cup',
    customer: 'customer service',
    cut: 'cutting vegetables',
    dad: 'father child',
    dance: 'dancing people',
    dangerous: 'danger sign',
    dark: 'dark night',
    date: 'calendar date',
    daughter: 'daughter family',
    day: 'sunny day',
    dear: 'dear letter',
    december: 'christmas december',
    decide: 'decision choice',
    delicious: 'delicious food',
    describe: 'describing picture',
    desk: 'office desk',
    detail: 'details document',
    dictionary: 'dictionary book',
    die: 'cemetery memorial',
    diet: 'healthy diet',
    difference: 'difference compare',
    different: 'different people',
    difficult: 'difficult task',
    dinner: 'dinner table',
    dirty: 'dirty shoes',
    doctor: 'doctor hospital',
    dog: 'dog pet',
    dollar: 'dollar money',
    door: 'door entrance',
    down: 'down stairs',
    draw: 'drawing art',
    dream: 'dream sleeping',
    dress: 'dress fashion',
    drink: 'drinking water',
    drive: 'driving car',
    driver: 'driver car',
    during: 'during meeting',
    each: 'each person',
    ear: 'human ear',
    early: 'early morning',
    east: 'east direction',
    easy: 'easy learning',
    eat: 'eating food',
    egg: 'egg breakfast',
    eight: 'number eight',
    eighteen: 'number eighteen',
    eighty: 'number eighty',
    eleven: 'number eleven',
    else: 'other choice',
    email: 'email inbox',
    end: 'finish line',
    enjoy: 'enjoy vacation',
    enough: 'enough food',
    evening: 'evening city',
    event: 'event audience',
    ever: 'time concept',
    every: 'daily routine',
    everyone: 'group of people',
    everything: 'many objects',
    exam: 'exam test',
    example: 'example notebook',
    excited: 'excited person',
    expensive: 'expensive luxury',
    explain: 'teacher explaining',
    eye: 'human eye',
    face: 'human face',
    fact: 'facts document',
    fall: 'fall autumn',
    family: 'happy family',
    famous: 'famous celebrity',
    far: 'long road',
    farm: 'farm field',
    farmer: 'farmer field',
    fast: 'running fast',
    fat: 'body shape',
    father: 'father child',
    favorite: 'favorite star',
    february: 'calendar february',
    feel: 'feeling emotion',
    festival: 'festival celebration',
    few: 'few objects',
    fifteen: 'number fifteen',
    fifth: 'number five',
    fifty: 'number fifty',
    film: 'movie film',
    find: 'search magnifier',
    fine: 'fine weather',
    finger: 'finger hand',
    finish: 'finish line',
    fire: 'fire flame',
    first: 'first place',
    fish: 'fish',
    five: 'number five',
    flat: 'apartment flat',
    flight: 'airplane flight',
    floor: 'floor room',
    flower: 'flower garden',
    fly: 'airplane flying',
    food: 'healthy food',
    foot: 'human foot',
    football: 'soccer ball',
    for: 'gift for you',
    forget: 'forget memory',
    form: 'form document',
    forty: 'number forty',
    four: 'number four',
    fourteen: 'number fourteen',
    free: 'free sign',
    friday: 'friday calendar',
    friend: 'friends together',
    from: 'travel from city',
    front: 'front door',
    fruit: 'fresh fruit',
    full: 'full plate',
    fun: 'fun children',
    funny: 'funny person laughing',
    game: 'board game',
    garden: 'garden flowers',
    geography: 'world map',
    get: 'getting package',
    girl: 'girl child',
    girlfriend: 'couple girlfriend',
    give: 'giving gift',
    glass: 'glass cup',
    go: 'person walking',
    good: 'thumbs up',
    goodbye: 'people saying goodbye',
    grandfather: 'grandfather family',
    grandmother: 'grandmother family',
    great: 'great success',
    green: 'green color nature',
    grey: 'grey color',
    group: 'group of people',
    grow: 'plant growing',
    guess: 'thinking person',
    guitar: 'guitar music',
    gym: 'gym fitness',
    hair: 'hair style',
    half: 'half orange',
    hand: 'human hand',
    happen: 'event happening',
    happy: 'happy person smiling',
    hard: 'hard work',
    hat: 'hat fashion',
    hate: 'angry emotion',
    have: 'person holding',
    he: 'man portrait',
    head: 'human head',
    health: 'health care',
    hear: 'listening ear',
    heart: 'heart love',
    hello: 'people waving hello',
    help: 'helping hand',
    her: 'woman portrait',
    here: 'location here',
    high: 'high mountain',
    him: 'man portrait',
    his: 'man portrait',
    history: 'history museum',
    hobby: 'hobby painting',
    holiday: 'holiday beach',
    home: 'cozy home',
    homework: 'student homework',
    hope: 'hope sunrise',
    horse: 'horse',
    hospital: 'hospital doctor',
    hot: 'hot weather',
    hotel: 'hotel room',
    hour: 'clock hour',
    house: 'family house',
    how: 'question mark',
    however: 'contrast concept',
    hundred: 'number one hundred',
    hungry: 'hungry person',
    husband: 'husband wife',
    i: 'person portrait',
    ice: 'ice cubes',
    idea: 'idea light bulb',
    if: 'question mark',
    imagine: 'imagination creative',
    important: 'important document',
    improve: 'progress improvement',
    in: 'inside room',
    include: 'including group',
    information: 'information data',
    interest: 'interest hobby',
    interested: 'interested student',
    interesting: 'interesting book',
    internet: 'internet technology',
    interview: 'job interview',
    into: 'entering door',
    invite: 'invitation card',
    island: 'island beach',
    it: 'object',
    jacket: 'jacket clothing',
    january: 'calendar january',
    jeans: 'jeans clothing',
    job: 'job interview',
    join: 'joining group',
    journey: 'journey road',
    juice: 'orange juice',
    july: 'calendar july',
    june: 'calendar june',
    just: 'just now clock',
    keep: 'keeping safe',
    key: 'key door',
    kitchen: 'kitchen room',
    know: 'knowledge books',
    land: 'landscape field',
    language: 'language learning',
    large: 'large building',
    last: 'last place',
    late: 'late clock',
    later: 'later clock',
    laugh: 'laughing person',
    learn: 'student learning',
    leave: 'leaving house',
    left: 'left direction',
    leg: 'human leg',
    lesson: 'lesson classroom',
    let: 'permission concept',
    letter: 'letter envelope',
    library: 'library books',
    lie: 'lying bed',
    life: 'life nature',
    light: 'light bulb',
    like: 'like thumbs up',
    line: 'line drawing',
    lion: 'lion',
    list: 'checklist',
    listen: 'listening headphones',
    little: 'small child',
    live: 'living room',
    local: 'local market',
    long: 'long road',
    look: 'looking eyes',
    lose: 'lost person',
    lot: 'many objects',
    love: 'love heart',
    lunch: 'lunch meal',
    machine: 'machine factory',
    magazine: 'magazine',
    main: 'main road',
    make: 'making craft',
    man: 'man portrait',
    many: 'many people',
    map: 'map travel',
    march: 'calendar march',
    market: 'market shopping',
    married: 'wedding couple',
    match: 'sports match',
    may: 'calendar may',
    maybe: 'thinking person',
    me: 'person portrait',
    meal: 'meal table',
    mean: 'meaning dictionary',
    meat: 'meat food',
    meet: 'meeting people',
    meeting: 'business meeting',
    member: 'team member',
    menu: 'restaurant menu',
    message: 'text message',
    meter: 'measuring tape',
    milk: 'milk glass',
    million: 'million money',
    minute: 'clock minute',
    miss: 'missing someone',
    mistake: 'mistake correction',
    model: 'model design',
    monday: 'monday calendar',
    money: 'money cash',
    month: 'calendar month',
    more: 'more sign',
    morning: 'morning sunrise',
    mother: 'mother child',
    mountain: 'mountain landscape',
    mouse: 'computer mouse',
    mouth: 'human mouth',
    move: 'moving boxes',
    movie: 'movie cinema',
    much: 'many objects',
    museum: 'museum gallery',
    music: 'music headphones',
    must: 'must do checklist',
    my: 'personal belongings',
    name: 'name tag',
    natural: 'natural landscape',
    near: 'near location',
    need: 'need help',
    negative: 'negative sign',
    neighbor: 'neighbor houses',
    never: 'never sign',
    new: 'new product',
    news: 'newspaper news',
    next: 'next arrow',
    nice: 'nice person smiling',
    night: 'night city',
    nine: 'number nine',
    nineteen: 'number nineteen',
    ninety: 'number ninety',
    no: 'no sign',
    north: 'north compass',
    nose: 'human nose',
    not: 'no sign',
    note: 'note paper',
    nothing: 'empty room',
    november: 'calendar november',
    now: 'now clock',
    number: 'numbers',
    nurse: 'nurse hospital',
    object: 'object on table',
    october: 'calendar october',
    of: 'group of objects',
    off: 'switch off',
    office: 'office workplace',
    often: 'daily routine',
    oil: 'cooking oil',
    old: 'old person',
    on: 'switch on',
    once: 'one time',
    one: 'number one',
    onion: 'onion vegetable',
    online: 'online learning',
    only: 'only one',
    open: 'open door',
    opinion: 'opinion discussion',
    opposite: 'opposite directions',
    or: 'choice options',
    orange: 'orange fruit',
    order: 'food order',
    other: 'other people',
    our: 'team group',
    out: 'outside door',
    outside: 'outside nature',
    over: 'over bridge',
    own: 'personal ownership',
    page: 'book page',
    paint: 'painting art',
    painting: 'painting art',
    pair: 'pair shoes',
    paper: 'paper documents',
    paragraph: 'writing paragraph',
    parent: 'parents family',
    park: 'park nature',
    part: 'part puzzle',
    partner: 'business partners',
    party: 'party celebration',
    passport: 'passport travel',
    past: 'old photos',
    pay: 'paying money',
    pen: 'pen writing',
    pencil: 'pencil writing',
    people: 'group of people',
    pepper: 'pepper spice',
    perfect: 'perfect score',
    period: 'time period',
    person: 'person portrait',
    phone: 'mobile phone',
    photo: 'photo camera',
    piano: 'piano music',
    picture: 'picture frame',
    piece: 'piece of cake',
    pig: 'pig farm',
    pink: 'pink color',
    place: 'location place',
    plan: 'planning calendar',
    plane: 'airplane',
    plant: 'plant pot',
    play: 'children playing',
    player: 'sports player',
    please: 'please help',
    point: 'pointing finger',
    police: 'police officer',
    pool: 'swimming pool',
    poor: 'poverty',
    popular: 'popular crowd',
    positive: 'positive thinking',
    possible: 'possible success',
    potato: 'potato vegetable',
    practice: 'practice learning',
    prefer: 'choice preference',
    prepare: 'preparing food',
    present: 'present gift',
    pretty: 'pretty flowers',
    price: 'price tag',
    probably: 'thinking person',
    problem: 'problem solving',
    product: 'product display',
    programme: 'computer program',
    project: 'project planning',
    purple: 'purple color',
    put: 'putting object',
    quarter: 'quarter coin',
    question: 'question mark',
    quick: 'running fast',
    quietly: 'quiet library',
    radio: 'radio device',
    rain: 'rainy weather',
    read: 'reading book',
    reader: 'book reader',
    ready: 'ready start',
    real: 'real life',
    really: 'surprised person',
    reason: 'reason thinking',
    red: 'red color',
    relax: 'relaxing sofa',
    remember: 'memory brain',
    repeat: 'repeat arrow',
    report: 'business report',
    restaurant: 'restaurant table',
    result: 'exam result',
    return: 'return arrow',
    rice: 'rice bowl',
    rich: 'money wealth',
    ride: 'riding bicycle',
    right: 'right direction',
    river: 'river landscape',
    road: 'road travel',
    room: 'living room',
    routine: 'daily routine',
    rule: 'rules document',
    run: 'running person',
    sad: 'sad person',
    salad: 'salad food',
    salt: 'salt spice',
    same: 'same objects',
    sandwich: 'sandwich',
    saturday: 'saturday calendar',
    say: 'speaking person',
    school: 'school classroom',
    science: 'science laboratory',
    scientist: 'scientist lab',
    sea: 'sea ocean',
    second: 'second place',
    section: 'document section',
    see: 'seeing eyes',
    sell: 'selling store',
    send: 'sending message',
    sentence: 'sentence writing',
    september: 'calendar september',
    seven: 'number seven',
    seventeen: 'number seventeen',
    seventy: 'number seventy',
    share: 'sharing people',
    she: 'woman portrait',
    shirt: 'shirt clothing',
    shoe: 'shoes',
    shop: 'shop store',
    shopping: 'shopping store',
    short: 'short person',
    should: 'advice consultation',
    show: 'show presentation',
    shower: 'bathroom shower',
    sick: 'sick person',
    similar: 'similar objects',
    sing: 'singing microphone',
    singer: 'singer microphone',
    sister: 'sisters family',
    sit: 'sitting chair',
    situation: 'situation discussion',
    six: 'number six',
    sixteen: 'number sixteen',
    sixty: 'number sixty',
    skill: 'learning skill',
    skirt: 'skirt clothing',
    sleep: 'sleeping bed',
    slow: 'slow turtle',
    small: 'small object',
    snake: 'snake',
    snow: 'snow winter',
    so: 'thinking person',
    some: 'some objects',
    someone: 'person silhouette',
    something: 'object on table',
    sometimes: 'sometimes clock',
    son: 'son family',
    song: 'music song',
    soon: 'soon clock',
    sorry: 'apologizing person',
    sound: 'sound speaker',
    soup: 'soup bowl',
    south: 'south compass',
    space: 'space stars',
    speak: 'speaking person',
    special: 'special gift',
    spell: 'spelling letters',
    spend: 'spending money',
    sport: 'sports equipment',
    spring: 'spring flowers',
    stand: 'standing person',
    star: 'star sky',
    start: 'starting line',
    statement: 'statement document',
    station: 'train station',
    stay: 'hotel stay',
    still: 'still water',
    stop: 'stop sign',
    story: 'story book',
    street: 'city street',
    strong: 'strong athlete',
    student: 'student studying',
    study: 'studying books',
    subject: 'school subject',
    success: 'success trophy',
    sugar: 'sugar cubes',
    summer: 'summer beach',
    sun: 'sun sky',
    sunday: 'sunday calendar',
    supermarket: 'supermarket aisle',
    sure: 'sure thumbs up',
    sweater: 'sweater clothing',
    swim: 'swimming pool',
    table: 'table furniture',
    take: 'taking photo',
    talk: 'people talking',
    tall: 'tall building',
    taxi: 'taxi car',
    tea: 'tea cup',
    teach: 'teacher teaching',
    teacher: 'teacher classroom',
    team: 'teamwork office',
    teenager: 'teenager student',
    telephone: 'telephone call',
    television: 'television',
    tell: 'telling story',
    ten: 'number ten',
    tennis: 'tennis court',
    terrible: 'terrible weather',
    test: 'exam test',
    text: 'text message',
    than: 'comparison concept',
    thank: 'thank you card',
    thanks: 'thank you card',
    that: 'pointing finger',
    the: 'book page',
    theater: 'theater stage',
    their: 'group belongings',
    them: 'group of people',
    then: 'then next',
    there: 'location there',
    they: 'group of people',
    thing: 'object on table',
    think: 'thinking person',
    third: 'third place',
    thirsty: 'drinking water',
    thirteen: 'number thirteen',
    thirty: 'number thirty',
    this: 'pointing object',
    thousand: 'number thousand',
    three: 'number three',
    through: 'through tunnel',
    thursday: 'thursday calendar',
    ticket: 'ticket travel',
    time: 'clock time',
    tired: 'tired person',
    title: 'book title',
    to: 'direction arrow',
    today: 'today calendar',
    together: 'friends together',
    toilet: 'toilet bathroom',
    tomato: 'tomato vegetable',
    tomorrow: 'tomorrow calendar',
    tonight: 'night city',
    too: 'too much',
    tooth: 'tooth dental',
    topic: 'topic discussion',
    tourist: 'tourist travel',
    town: 'small town',
    traffic: 'traffic road',
    train: 'train station',
    travel: 'travel luggage',
    tree: 'tree nature',
    trip: 'travel trip',
    trousers: 'trousers clothing',
    true: 'true check mark',
    try: 'trying hard',
    tuesday: 'tuesday calendar',
    turn: 'turn direction',
    twelve: 'number twelve',
    twenty: 'number twenty',
    two: 'number two',
    type: 'typing keyboard',
    uncle: 'family man',
    understand: 'understanding idea',
    university: 'university campus',
    until: 'waiting clock',
    up: 'up arrow',
    us: 'group of people',
    use: 'using laptop',
    useful: 'useful tool',
    usually: 'daily routine',
    vacation: 'vacation beach',
    vegetable: 'vegetables',
    very: 'very happy',
    video: 'video camera',
    village: 'village houses',
    visit: 'visiting museum',
    visitor: 'visitor tourist',
    wait: 'waiting person',
    waiter: 'waiter restaurant',
    wake: 'waking up',
    walk: 'walking person',
    wall: 'wall room',
    want: 'shopping desire',
    warm: 'warm sweater',
    wash: 'washing hands',
    watch: 'watch wristwatch',
    water: 'glass of water',
    way: 'road way',
    we: 'group of people',
    wear: 'wearing clothes',
    weather: 'weather forecast',
    website: 'website screen',
    wednesday: 'wednesday calendar',
    week: 'calendar week',
    weekend: 'weekend relaxing',
    welcome: 'welcome sign',
    well: 'wellness health',
    west: 'west compass',
    what: 'question mark',
    when: 'clock question',
    where: 'map location',
    which: 'choice options',
    white: 'white color',
    who: 'people question',
    why: 'question mark',
    wife: 'wife husband',
    will: 'future planning',
    win: 'winner trophy',
    window: 'window house',
    wine: 'wine glass',
    winter: 'winter snow',
    with: 'people together',
    without: 'alone person',
    woman: 'woman portrait',
    wonderful: 'wonderful landscape',
    word: 'word dictionary',
    work: 'office work',
    worker: 'worker construction',
    world: 'world map',
    would: 'question request',
    write: 'writing notebook',
    writer: 'writer writing',
    wrong: 'wrong answer',
    yard: 'garden yard',
    year: 'calendar year',
    yellow: 'yellow color',
    yes: 'yes check mark',
    yesterday: 'yesterday calendar',
    you: 'person pointing',
    young: 'young people',
    your: 'personal belongings',
    zero: 'number zero',
  };

  if (queryMap[cleanWord]) {
    return queryMap[cleanWord];
  }

  if (type === 'v') {
    return `${cleanWord} action`;
  }

  if (type === 'adj') {
    return `${cleanWord} concept`;
  }

  if (type === 'adv') {
    return `${cleanWord} concept`;
  }

  if (type === 'pre' || type === 'con' || type === 'pro' || type === 'det') {
    return `${cleanWord} english grammar concept`;
  }

  return cleanWord;
}

function fetchPexelsImage(query) {
  return new Promise((resolve, reject) => {
    const url = `https://api.pexels.com/v1/search?query=${encodeURIComponent(
      query,
    )}&per_page=1&orientation=landscape`;

    const req = https.get(
      url,
      {
        headers: {
          Authorization: PEXELS_API_KEY,
        },
      },
      (res) => {
        let data = '';

        res.on('data', (chunk) => {
          data += chunk;
        });

        res.on('end', () => {
          try {
            const json = JSON.parse(data);

            if (json.error) {
              return reject(new Error(json.error));
            }

            if (!json.photos || json.photos.length === 0) {
              return resolve(null);
            }

            const photo = json.photos[0];

            return resolve({
              imageUrl:
                photo.src?.large ||
                photo.src?.medium ||
                photo.src?.landscape ||
                null,
              photographer: photo.photographer,
              pexelsUrl: photo.url,
            });
          } catch (error) {
            reject(error);
          }
        });
      },
    );

    req.on('error', reject);
  });
}

async function main() {
  if (!MONGO_URL) {
    throw new Error('Missing MONGO_URL_LOCAL or MONGO_URL');
  }

  if (!PEXELS_API_KEY) {
    throw new Error('Missing PEXELS_API_KEY in backend/.env');
  }

  await mongoose.connect(MONGO_URL, {
    useUnifiedTopology: true,
    useNewUrlParser: true,
    useCreateIndex: true,
  });

  console.log('MongoDB connected');

  const words = await WordModel.find({
    $or: [
      { picture: null },
      { picture: '' },
      { picture: { $in: DEFAULT_IMAGES } },
      { picture: /loremflickr/i },
      { picture: /1516321318423-f06f85e504b3/i },
    ],
  })
    .select('word mean type picture note')
    .limit(LIMIT_PER_RUN);

  console.log(`Words need image update: ${words.length}`);

  let updated = 0;
  let skipped = 0;
  let failed = 0;

  for (const item of words) {
    try {
      const query = getBetterSearchQuery(item.word, item.mean, item.type);
      const result = await fetchPexelsImage(query);

      if (!result || !result.imageUrl) {
        skipped++;
        console.log(`No image: ${item.word} -> ${query}`);
        await sleep(1200);
        continue;
      }

      item.picture = result.imageUrl;
      item.note = item.note
        ? `${item.note}`
        : `Ảnh: ${result.photographer} / Pexels`;

      await item.save();

      updated++;
      console.log(`Updated ${updated}: ${item.word} -> ${query}`);

      await sleep(1200);
    } catch (error) {
      failed++;
      console.log(`Failed: ${item.word}`);
      console.log(error.message);
      await sleep(1500);
    }
  }

  console.log('======================');
  console.log(`Updated: ${updated}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Failed: ${failed}`);
  console.log('DONE');

  await mongoose.disconnect();
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});